version: "3"

services:
  nginx:
    restart: always
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/docker/nginx/conf.d:/etc/nginx/conf.d
      - /var/docker/nginx/vhost.d:/etc/nginx/vhost.d
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/letsencrypt-nginx-proxy/certs:/etc/nginx/certs:ro
      - /var/docker/nginx/htpasswd:/etc/nginx/htpasswd:ro

  nginx-gen:
    restart: always
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - /var/docker/nginx/conf.d:/etc/nginx/conf.d
      - /var/docker/nginx/vhost.d:/etc/nginx/vhost.d
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/letsencrypt-nginx-proxy/certs:/etc/nginx/certs:ro
      - /var/docker/nginx/htpasswd:/etc/nginx/htpasswd:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./volumes/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    command: -notify-sighup nginx-web -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf

  letsencrypt-nginx-proxy-companion:
    restart: always
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    volumes:
      - /var/docker/nginx/conf.d:/etc/nginx/conf.d
      - /var/docker/nginx/vhost.d:/etc/nginx/vhost.d
      - /var/docker/nginx/html:/usr/share/nginx/html
      - /var/docker/letsencrypt-nginx-proxy/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - NGINX_PROXY_CONTAINER=nginx-web

networks:
  proxy-tier:
    external:
      name: nginx-proxy
